### ISSUE TITLE
Issue with Changing Network Configuration on Jackal Robot (Netplan)

### ISSUE THREAD

**Issue by MohamedHabbad** [jackal/jackal#142]
Hey everyone,

I'm currently facing an issue while trying to change the network configuration on my Jackal robot. I want to assign a specific IP address, "192.168.131.3," to the Ethernet port "enp3s0" on the robot. However, despite editing the YAML configuration file and running sudo netplan apply, the changes don't seem to take effect.
![ifconfig111](https://github.com/jackal/jackal/assets/136476747/425a4a0d-9a86-4ec6-b568-8e2888ad0ad3)
Here's the content of the YAML file I modified (/etc/netplan/50-clearpath-bridge.yaml):
![Netplan](https://github.com/jackal/jackal/assets/136476747/505e6daf-617d-4a95-89ab-93c35ba64da0)
I made sure to save the changes and ran sudo netplan apply to apply the new configuration. However, the IP address of the "enp3s0" port remains unchanged.

I'm not sure what could be causing this issue. I would greatly appreciate any insights or suggestions on how to troubleshoot and resolve this problem. Am I missing any additional steps or configurations?

PS : i can change the IP with this : sudo ip addr add 192.168.131.3/24 broadcast 192.168.131.255 dev enp3s0 
and it will work properly but after turning off the Jackal and turning it on again it backs to the previous configuration, and that's why i want to change it permanently.
Thank you in advance for your help!

**Comment by civerachb-cpr** [comment]
Your `enp3s0` interface is still being matched by the `bridge_en` match rule: all interfaces matching the form `en*` are bridged by that rule.

I would suggest modifying the file like this:

```
network:
  version: 2
  renderer: networkd
  ethernets:
    enp3s0:
      dhcp4: no
      dhcp6: no
      addresses:
        - 192.168.131.3/24
    bridge_eth:
      dhcp4: no
      dhcp6: no
      match:
        name: eth*
    # rename bridge_en to bridge_en0
    bridge_eno:
      dhcp4: no
      dhcp6: no
      match:
        # change en* to eno* to match eno1
        name: eno*
    # optional: add enx* to handle ethernet-over-USB devices
    bridge_enx:
      dhcp4: no
      dhcp6: no
      match:
        name: enx*
  bridges:
    br0:
      dhcp4: yes
      dhcp6: no
      # change the interfaces array to use eno & enx bridges
      interfaces: [bridge_eth, bridge_eno, bridge_enx]
      addresses:
        - 192.168.131.1/24
```

Why do you need the main computer in the Jackal to have two addresses on the `192.168.131.0/24` subnet?

Also, please be aware that the `192.168.131.0/24` subnet may have multiple devices on it, depending on how your Jackal was integrated.  Please check the manual that came with your robot and see https://docs.clearpathrobotics.com/docs/tools/network_ip_addresses for reserved IP addresses to make sure you don't accidentally clobber an existing device's address.  (.3 is normally free, but it is in the reserved range for secondary processors inside the robot.)
